### ISSUE TITLE
Getting “Unauthorized” in logs. 

### ISSUE THREAD

**Issue by sdwhwk** [joshgetter/hassio-addons#23]
I just installed the addon and when I try to run it, I get this in the logs:

`info: System.Net.Http.HttpClient.KasaHttpClient.LogicalHandler[101]
      End processing HTTP request after 1348.6954ms - 401
fail: KasaStreamer.KasaStreamReader[0]
      [kitchen] An error occurred while reading camera stream.
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
         at KasaStreamer.KasaStreamReader.StartSplittingStream(CancellationToken cancellationToken) in /KasaStreamer/KasaStreamer/KasaStreamReader.cs:line 117 `

Just for giggles, I changed my password to log in to abcd1234 just to see if that was the problem (had a complicated password) and it still gave me this. 

Running HA 2023.11.2.

**Comment by vmhomelab** [comment]
Same here. Any luck?
