### ISSUE TITLE
Verified Support for Kasa Cameras

### ISSUE THREAD

**Issue by tmarks21** [joshgetter/hassio-addons#24]
Great Add-on! I was able to get everything up and running on my instance. I just wanted to post that I was able to get camera feeds for the following KASA Cameras. 

[KC420WS](https://a.co/d/3HSU1DZ) - Outdoor Camera
[EC70](https://a.co/d/4gGCKNb) - PZT Indoor Camera
[KD110](https://a.co/d/hrbZR52) - Video Doorbell

The feeds for these cameras work great and seem to provide consistent feed. 

- Enhancement requests would be to enable PZT Control for the EC70 or use the zones features? 
- For the outdoor camera it would be cool to be able to enable to the spotlight on the camera from HASS
- ability to trigger automations based on motion / person events if possible

Thanks for your hard work on this addon.

**Comment by cccrll** [comment]
Hi, I've been able to add a KC120 and a KC110 camera, but I get error messages with my KC420WS...what settings did you use for your KC420WS camera?

**Comment by cccrll** [comment]
I'm constantly getting this error message:

KasaStreamer.KasaStreamReader[0]
      [Terrasse_Camera] An error occurred while reading camera stream.
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
         at KasaStreamer.KasaStreamReader.StartSplittingStream(CancellationToken cancellationToken) in /KasaStreamer/

**Comment by iVolt1** [comment]
I get the same error message.  Any hints?

fail: KasaStreamer.KasaStreamReader[0]
      [SWCorner] An error occurred while reading camera stream.
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
         at KasaStreamer.KasaStreamReader.StartSplittingStream(CancellationToken cancellationToken) in /KasaStreamer/KasaStreamer/KasaStreamReader.cs:line 117
