### ISSUE TITLE
Standalone Docker Container

### ISSUE THREAD

**Issue by TheRealFalseReality** [joshgetter/hassio-addons#28]
Can this be configured as a standalone Docker container? It's work well, but I have 5 cameras so it simply takes up my entire CPU usage (RPi4). I would like to use this on my LinuxMint machine in Docker, I am using a fork gryphy/amd64-kasa-camera but I would like to use your updated.

I did manage to get this started as a docker container, but I get the following error:
`Unhandled exception. System.InvalidOperationException: A suitable constructor for type 'KasaStreamer.Camera' could not be located. Ensure the type is concrete and all parameters of a public constructor are either registered as services or passed as arguments. Also ensure no extraneous arguments are provided.`

Logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Starting Nginx
Nginx Started
Starting controller
Starting KasaStreamer
Unhandled exception. System.InvalidOperationException: A suitable constructor for type 'KasaStreamer.Camera' could not be located. Ensure the type is concrete and all parameters of a public constructor are either registered as services or passed as arguments. Also ensure no extraneous arguments are provided.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at KasaStreamer.Controller.StartAsync(CancellationToken cancellationToken) in /KasaStreamer/KasaStreamer/Controller.cs:line 82
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at KasaStreamer.Program.Main(String[] args) in /KasaStreamer/KasaStreamer/Program.cs:line 20
/run.sh: line 11:   204 Aborted                 (core dumped) dotnet KasaStreamer.dll
[cmd] /run.sh exited 134
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

`options.json`
```
{
    "kasausername": "REDACTED",
    "kasapassword": "REDACTED",
    "cameras": {
        "cameraip": "192.168.XX.XXX",
        "cameraname": "FrontCamera"
    },
    "retrylimit": 5,
    "retrysleep": 30.0,
    "toggleentity": ""
}
```

Thanks for any help!

**Comment by Serk72** [comment]
I was able to get a docker image of it building and running by upgrading the libaries used and using an alpine base image
https://github.com/joshgetter/hassio-addons/compare/master...Serk72:hassio-addons:master

havent finished what I want to do with it yet as i want to get it running on kubernetes via helm,
but the docker image at least seems to work with these changes
https://hub.docker.com/r/serk72/kasa-camera-addon/tags

**Comment by TheRealFalseReality** [comment]
Nice! I went ahead and moved to Frigate, which has go2rtc for Kasa cams built in. It's works well with Frigate as a docker on another Linux machine
